### PR TITLE
Load a screens worth

### PR DESCRIPTION
**Pull request by mixmix**
This PR should be reviewed after : https://github.com/pull-stream/pull-scroll/pull/1

---

It also depends on the changes to hypertabs here : https://github.com/dominictarr/hypertabs/pull/4

It changes the problematic _"just add 10 messsages to hidden tabs"_ and instead adds messages until they are piled up slightly higher than the `window.innerHeight`. This means that pull-scroll will work with ANY size screen + message. 

**TODO after this is merged :** 
- [ ] bump patchbay deps!

### CODE REVIEW

**Comment by dominictarr** [comment]
have tested this is patchbay and confirm it works.

**Comment by dominictarr** [comment]
merged into 3.0.0

**Comment by dominictarr** [comment]
ah, actually there is something wrong here. This is loading way too much, and cpu is spinning, scroll not smooth.

notice that the scroll bar handle just gets really small (because it adds more items whenever the page scrolls!) compare this behaviour with 0.3.4

**Comment by mixmix** [comment]
arg, I tried it but didn't see that. I'll check over the logic and see if I can fix that.

**Comment by mixmix** [comment]
fix here hopefully : https://github.com/pull-stream/pull-scroll/pull/3

**Pull request merged**
